-- cleanup *all* app tables
DROP TABLE IF EXISTS AppUser CASCADE;

DROP TABLE IF EXISTS Profile CASCADE;

DROP TABLE IF EXISTS UsersPref CASCADE;

DROP TABLE IF EXISTS Preferences CASCADE;

DROP TABLE IF EXISTS EventType CASCADE;

DROP TABLE IF EXISTS UsersInEvent CASCADE;

DROP TABLE IF EXISTS UsersInGroup CASCADE;

DROP TABLE IF EXISTS AppGroup CASCADE;

DROP TABLE IF EXISTS Event CASCADE;
