-- clean *all* data
TRUNCATE Auth CASCADE;

TRUNCATE Profile CASCADE;

TRUNCATE Preferences CASCADE;

TRUNCATE UsersPref CASCADE;

TRUNCATE UsersInGroup CASCADE;

TRUNCATE UsersInEvent CASCADE;

TRUNCATE AppGroup CASCADE;

TRUNCATE Event CASCADE;

TRUNCATE EventType CASCADE;

TRUNCATE Messages CASCADE;
